package utils.mytypes;

public enum HobbyType {
    SINGING,
    DANCING,
    SKIING,
    HELPING,
    PAINTING,
    PROGRAMMING,
    SOLVING_PROBLEMS,
    BEING_BEAUTIFUL,
    COMPLAINT,
    BEING_AWKWARD,
    PLAYING_GUITAR,
    EXERCISING,
    POWERLIFTING,
    ACTING
}
